begin;

create extension if not exists pgcrypto with schema extensions;
create schema if not exists cn_demo;

revoke all on schema cn_demo from public, anon, authenticated;

create table cn_demo.admins (
  id bigint generated by default as identity primary key,
  username text not null unique check (username = lower(username) and length(username) between 3 and 40),
  password_hash text not null,
  fullname text not null check (length(fullname) between 1 and 100),
  status text not null default 'Active' check (status in ('Active', 'Inactive')),
  language text not null default 'en' check (language in ('en', 'zh')),
  protected boolean not null default false,
  is_baseline boolean not null default false,
  created_at timestamptz not null default clock_timestamp()
);

create table cn_demo.teachers (
  id bigint generated by default as identity primary key,
  username text not null unique check (username = lower(username) and length(username) between 3 and 40),
  password_hash text not null,
  fullname text not null check (length(fullname) between 1 and 100),
  color text not null default '#2563eb' check (color ~ '^#[0-9a-fA-F]{6}$'),
  status text not null default 'Active' check (status in ('Active', 'Inactive')),
  language text not null default 'en' check (language in ('en', 'zh')),
  protected boolean not null default false,
  is_baseline boolean not null default false,
  created_at timestamptz not null default clock_timestamp()
);

create table cn_demo.students (
  id bigint generated by default as identity primary key,
  name text not null check (length(name) between 1 and 100),
  notes text not null default '' check (length(notes) <= 1000),
  teacher_id bigint references cn_demo.teachers(id) on update restrict on delete restrict,
  status text not null default 'Active' check (status in ('Active', 'Inactive', 'End of Contract')),
  username text unique check (username is null or (username = lower(username) and length(username) between 3 and 40)),
  password_hash text,
  language text not null default 'en' check (language in ('en', 'zh')),
  protected boolean not null default false,
  is_baseline boolean not null default false,
  created_at timestamptz not null default clock_timestamp(),
  constraint students_login_pair_check check ((username is null) = (password_hash is null))
);

create table cn_demo.schedules (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references cn_demo.teachers(id) on update restrict on delete restrict,
  date date not null,
  timeslot text not null check (length(timeslot) between 3 and 40),
  student text not null check (length(student) between 1 and 300),
  student_id bigint references cn_demo.students(id) on update restrict on delete restrict,
  student_ids bigint[] not null default '{}',
  note text not null default '' check (length(note) <= 1000),
  trial boolean not null default false,
  cancelled boolean not null default false,
  cancel_reason text not null default '' check (length(cancel_reason) <= 500),
  is_baseline boolean not null default false,
  created_at timestamptz not null default clock_timestamp()
);

create table cn_demo.reports (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null unique references cn_demo.schedules(id) on update restrict on delete cascade,
  teacher_id bigint not null references cn_demo.teachers(id) on update restrict on delete restrict,
  content text not null default '' check (length(content) <= 10000),
  absent boolean not null default false,
  images jsonb not null default '[]'::jsonb check (jsonb_typeof(images) = 'array'),
  date date not null,
  submitted_at timestamptz not null default clock_timestamp(),
  link text not null default '' check (length(link) <= 1000),
  book text not null default '' check (length(book) <= 200),
  pages text not null default '' check (length(pages) <= 100),
  class_duration text not null default '' check (length(class_duration) <= 100),
  absent_reason text not null default '' check (length(absent_reason) <= 200),
  absent_other text not null default '' check (length(absent_other) <= 500),
  tracker_remarks text not null default '' check (length(tracker_remarks) <= 2000),
  is_baseline boolean not null default false
);

create table cn_demo.report_drafts (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references cn_demo.schedules(id) on update restrict on delete cascade,
  teacher_id bigint not null references cn_demo.teachers(id) on update restrict on delete restrict,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  updated_at timestamptz not null default clock_timestamp(),
  unique (schedule_id, teacher_id)
);

create table cn_demo.class_transactions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references cn_demo.students(id) on update restrict on delete restrict,
  receipt_no text not null default '' check (length(receipt_no) <= 80),
  type text not null check (type in ('purchase', 'monthly-fee', 'monthly-fee-payment', 'transfer', 'adjustment', 'manual', 'compensation', 'promo', 'recommendation', 'refund', 'cancel-monthly-fee')),
  total_classes integer not null default 0 check (total_classes between -10000 and 10000),
  remaining_classes integer not null default 0 check (remaining_classes between -10000 and 10000),
  teacher_id bigint references cn_demo.teachers(id) on update restrict on delete restrict,
  from_student_id bigint references cn_demo.students(id) on update restrict on delete restrict,
  status text not null default '' check (length(status) <= 40),
  amount numeric(12,2),
  transaction_no text not null default '' check (length(transaction_no) <= 80),
  date date not null,
  due_date date,
  notes text not null default '' check (length(notes) <= 1000),
  is_baseline boolean not null default false,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp()
);

create table cn_demo.class_usage (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references cn_demo.class_transactions(id) on update restrict on delete cascade,
  schedule_id bigint references cn_demo.schedules(id) on update restrict on delete set null,
  date date not null,
  time text not null default '',
  duration text not null default '',
  materials text not null default '',
  pages text not null default '',
  remarks text not null default '',
  charged boolean not null default true,
  is_baseline boolean not null default false,
  created_at timestamptz not null default clock_timestamp()
);

create table cn_demo.notifications (
  id bigint generated by default as identity primary key,
  message text not null check (length(message) between 1 and 500),
  type text not null default 'info' check (type in ('info', 'success', 'warning', 'error')),
  student_name text not null default '',
  teacher_id bigint references cn_demo.teachers(id) on delete cascade,
  admin_id bigint references cn_demo.admins(id) on delete cascade,
  student_id bigint references cn_demo.students(id) on delete cascade,
  read boolean not null default false,
  created_at timestamptz not null default clock_timestamp()
);

create table cn_demo.sessions (
  token_hash text primary key check (token_hash ~ '^[0-9a-f]{64}$'),
  role text not null check (role in ('admin', 'teacher', 'student')),
  user_id bigint not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default clock_timestamp()
);

create table cn_demo.uploads (
  id bigint generated by default as identity primary key,
  session_token_hash text not null check (session_token_hash ~ '^[0-9a-f]{64}$'),
  object_path text not null unique check (object_path ~ '^visitor/[0-9a-f-]{36}/[0-9a-f-]{36}\.(webp|png|jpe?g)$'),
  size_bytes integer not null check (size_bytes between 1 and 2097152),
  logical_date date not null,
  created_at timestamptz not null default clock_timestamp()
);

create table cn_demo.login_rate_limits (
  attempt_key text primary key check (length(attempt_key) between 1 and 64),
  failed_count integer not null default 0 check (failed_count between 0 and 20),
  locked_until timestamptz,
  updated_at timestamptz not null default clock_timestamp()
);

create table cn_demo.activity_logs (
  id bigint generated by default as identity primary key,
  actor_role text not null check (actor_role in ('public', 'admin', 'teacher', 'student', 'system')),
  actor_id bigint,
  action text not null check (length(action) between 1 and 80),
  status integer not null check (status between 100 and 599),
  created_at timestamptz not null default clock_timestamp()
);

create or replace function cn_demo.protect_demo_account()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if lower(coalesce(new.username, '')) = 'devpau' then
    raise exception using errcode = '23514', message = 'reserved demo username';
  end if;

  if tg_op = 'DELETE' and old.protected and current_setting('cn_demo.reset_context', true) <> 'on' then
    raise exception using errcode = '42501', message = 'protected demo account';
  end if;

  if tg_op = 'UPDATE' and old.protected and current_setting('cn_demo.reset_context', true) <> 'on' then
    if new.username is distinct from old.username or new.password_hash is distinct from old.password_hash then
      raise exception using errcode = '42501', message = 'protected demo credential';
    end if;
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create or replace function cn_demo.hash_password(p_password text)
returns text
language sql
security definer
set search_path = ''
as $$
  select case
    when length(p_password) between 8 and 72
      then extensions.crypt(p_password, extensions.gen_salt('bf', 10))
    else null
  end;
$$;

create or replace function cn_demo.verify_password(p_password text, p_password_hash text)
returns boolean
language sql
security definer
set search_path = ''
as $$
  select
    length(p_password) between 1 and 72
    and p_password_hash is not null
    and extensions.crypt(p_password, p_password_hash) = p_password_hash;
$$;

create trigger protect_admin_account
before insert or update or delete on cn_demo.admins
for each row execute function cn_demo.protect_demo_account();

create trigger protect_teacher_account
before insert or update or delete on cn_demo.teachers
for each row execute function cn_demo.protect_demo_account();

create trigger protect_student_account
before insert or update or delete on cn_demo.students
for each row execute function cn_demo.protect_demo_account();

create or replace function cn_demo.reset_demo_data(p_logical_date date)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_logical_date is null then
    raise exception using errcode = '22004', message = 'logical date is required';
  end if;

  perform set_config('cn_demo.reset_context', 'on', true);

  delete from cn_demo.sessions;
  delete from cn_demo.uploads;
  delete from cn_demo.login_rate_limits;
  delete from cn_demo.notifications;
  delete from cn_demo.report_drafts;
  delete from cn_demo.class_usage;
  delete from cn_demo.reports where not is_baseline;
  delete from cn_demo.class_transactions where not is_baseline;
  delete from cn_demo.schedules where not is_baseline;
  delete from cn_demo.students where not is_baseline;
  delete from cn_demo.teachers where not is_baseline;
  delete from cn_demo.admins where not is_baseline;
  delete from cn_demo.activity_logs;

  insert into cn_demo.admins (id, username, password_hash, fullname, status, protected, is_baseline)
  values (1, 'admin', extensions.crypt('password', extensions.gen_salt('bf', 10)), 'Preview Administrator', 'Active', true, true)
  on conflict (id) do update set
    username = excluded.username,
    password_hash = excluded.password_hash,
    fullname = excluded.fullname,
    status = excluded.status,
    language = 'en',
    protected = true,
    is_baseline = true;

  insert into cn_demo.teachers (id, username, password_hash, fullname, color, status, protected, is_baseline)
  values
    (1, 'testteacher', extensions.crypt('password', extensions.gen_salt('bf', 10)), 'Preview Teacher A', '#2563eb', 'Active', true, true),
    (2, 'preview-teacher-b', extensions.crypt(encode(extensions.gen_random_bytes(24), 'hex'), extensions.gen_salt('bf', 10)), 'Preview Teacher B', '#7c3aed', 'Active', false, true),
    (3, 'preview-teacher-c', extensions.crypt(encode(extensions.gen_random_bytes(24), 'hex'), extensions.gen_salt('bf', 10)), 'Preview Teacher C', '#059669', 'Active', false, true)
  on conflict (id) do update set
    username = excluded.username,
    password_hash = excluded.password_hash,
    fullname = excluded.fullname,
    color = excluded.color,
    status = excluded.status,
    language = 'en',
    protected = excluded.protected,
    is_baseline = true;

  insert into cn_demo.students (id, name, notes, teacher_id, status, username, password_hash, protected, is_baseline)
  values
    (1, 'Preview Student A', 'Generated sample student for portfolio preview.', 1, 'Active', 'teststudent', extensions.crypt('password', extensions.gen_salt('bf', 10)), true, true),
    (2, 'Preview Student B', 'Generated sample student for portfolio preview.', 2, 'Active', null, null, false, true),
    (3, 'Preview Student C', 'Generated sample student for portfolio preview.', 1, 'Active', null, null, false, true),
    (4, 'Preview Student D', 'Generated sample student for portfolio preview.', 3, 'Active', null, null, false, true),
    (5, 'Preview Student E', 'Generated sample student for portfolio preview.', 2, 'Active', null, null, false, true),
    (6, 'Preview Student F', 'Generated sample student for portfolio preview.', 3, 'Active', null, null, false, true)
  on conflict (id) do update set
    name = excluded.name,
    notes = excluded.notes,
    teacher_id = excluded.teacher_id,
    status = excluded.status,
    username = excluded.username,
    password_hash = excluded.password_hash,
    language = 'en',
    protected = excluded.protected,
    is_baseline = true;

  insert into cn_demo.schedules (id, teacher_id, date, timeslot, student, student_id, student_ids, note, is_baseline)
  values
    (1, 1, p_logical_date - 2, '09:00 - 09:30', 'Preview Student A', 1, array[1]::bigint[], 'Generated completed class for report preview.', true),
    (2, 2, p_logical_date - 1, '14:00 - 14:45', 'Preview Student B, Preview Student C', 2, array[2,3]::bigint[], 'Generated group class for report preview.', true),
    (3, 1, p_logical_date, '10:00 - 10:30', 'Preview Student B', 2, array[2]::bigint[], 'Generated class scheduled for today.', true),
    (4, 3, p_logical_date, '16:00 - 16:30', 'Preview Student D', 4, array[4]::bigint[], 'Generated class scheduled for today.', true),
    (5, 2, p_logical_date + 1, '11:00 - 11:30', 'Preview Student E', 5, array[5]::bigint[], 'Generated upcoming class.', true),
    (6, 1, p_logical_date + 2, '13:00 - 13:30', 'Preview Student C', 3, array[3]::bigint[], 'Generated upcoming class.', true),
    (7, 3, p_logical_date + 3, '15:00 - 15:45', 'Preview Student F', 6, array[6]::bigint[], 'Generated upcoming class.', true)
  on conflict (id) do update set
    teacher_id = excluded.teacher_id,
    date = excluded.date,
    timeslot = excluded.timeslot,
    student = excluded.student,
    student_id = excluded.student_id,
    student_ids = excluded.student_ids,
    note = excluded.note,
    trial = false,
    cancelled = false,
    cancel_reason = '',
    is_baseline = true;

  insert into cn_demo.reports (id, schedule_id, teacher_id, content, date, book, pages, class_duration, tracker_remarks, is_baseline)
  values
    (1, 1, 1, 'Generated preview report: lesson goals were completed and the student participated well.', p_logical_date - 2, 'Preview Workbook 1', '12-15', '30 minutes', 'Fictional progress entry for preview only.', true),
    (2, 2, 2, 'Generated preview report: the class practiced vocabulary and short conversations.', p_logical_date - 1, 'Preview Conversation Guide', '8-10', '45 minutes', 'Fictional group-class entry for preview only.', true)
  on conflict (id) do update set
    schedule_id = excluded.schedule_id,
    teacher_id = excluded.teacher_id,
    content = excluded.content,
    date = excluded.date,
    book = excluded.book,
    pages = excluded.pages,
    class_duration = excluded.class_duration,
    tracker_remarks = excluded.tracker_remarks,
    absent = false,
    images = '[]'::jsonb,
    submitted_at = clock_timestamp(),
    link = '',
    absent_reason = '',
    absent_other = '',
    is_baseline = true;

  insert into cn_demo.class_transactions (id, student_id, receipt_no, type, total_classes, remaining_classes, teacher_id, status, transaction_no, date, notes, is_baseline)
  values
    (1, 1, 'DEMO-RC-001', 'purchase', 12, 8, 1, '', 'DEMO-TXN-001', p_logical_date - 10, 'Generated preview purchase.', true),
    (2, 2, 'DEMO-RC-002', 'purchase', 10, 6, 2, '', 'DEMO-TXN-002', p_logical_date - 8, 'Generated preview purchase.', true),
    (3, 3, 'DEMO-RC-003', 'purchase', 8, 5, 1, '', 'DEMO-TXN-003', p_logical_date - 6, 'Generated preview purchase.', true),
    (4, 4, 'DEMO-RC-004', 'monthly-fee', 0, 0, 3, 'active', 'DEMO-TXN-004', p_logical_date - 4, 'Generated preview monthly plan.', true)
  on conflict (id) do update set
    student_id = excluded.student_id,
    receipt_no = excluded.receipt_no,
    type = excluded.type,
    total_classes = excluded.total_classes,
    remaining_classes = excluded.remaining_classes,
    teacher_id = excluded.teacher_id,
    status = excluded.status,
    transaction_no = excluded.transaction_no,
    date = excluded.date,
    notes = excluded.notes,
    from_student_id = null,
    amount = null,
    due_date = null,
    updated_at = clock_timestamp(),
    is_baseline = true;

  insert into cn_demo.class_usage (id, transaction_id, schedule_id, date, time, duration, materials, pages, remarks, charged, is_baseline)
  values
    (1, 1, 1, p_logical_date - 2, '09:00', '30 minutes', 'Preview Workbook 1', '12-15', 'Generated usage entry.', true, true),
    (2, 2, 2, p_logical_date - 1, '14:00', '45 minutes', 'Preview Conversation Guide', '8-10', 'Generated usage entry.', true, true)
  on conflict (id) do update set
    transaction_id = excluded.transaction_id,
    schedule_id = excluded.schedule_id,
    date = excluded.date,
    time = excluded.time,
    duration = excluded.duration,
    materials = excluded.materials,
    pages = excluded.pages,
    remarks = excluded.remarks,
    charged = true,
    is_baseline = true;

  perform setval(pg_get_serial_sequence('cn_demo.admins', 'id'), greatest(999, (select max(id) from cn_demo.admins)), true);
  perform setval(pg_get_serial_sequence('cn_demo.teachers', 'id'), greatest(999, (select max(id) from cn_demo.teachers)), true);
  perform setval(pg_get_serial_sequence('cn_demo.students', 'id'), greatest(999, (select max(id) from cn_demo.students)), true);
  perform setval(pg_get_serial_sequence('cn_demo.schedules', 'id'), greatest(999, (select max(id) from cn_demo.schedules)), true);
  perform setval(pg_get_serial_sequence('cn_demo.reports', 'id'), greatest(999, (select max(id) from cn_demo.reports)), true);
  perform setval(pg_get_serial_sequence('cn_demo.class_transactions', 'id'), greatest(999, (select max(id) from cn_demo.class_transactions)), true);
  perform setval(pg_get_serial_sequence('cn_demo.class_usage', 'id'), greatest(999, (select max(id) from cn_demo.class_usage)), true);
end;
$$;

select cn_demo.reset_demo_data((clock_timestamp() at time zone 'Asia/Manila')::date);

alter table cn_demo.admins enable row level security;
alter table cn_demo.teachers enable row level security;
alter table cn_demo.students enable row level security;
alter table cn_demo.schedules enable row level security;
alter table cn_demo.reports enable row level security;
alter table cn_demo.report_drafts enable row level security;
alter table cn_demo.class_transactions enable row level security;
alter table cn_demo.class_usage enable row level security;
alter table cn_demo.notifications enable row level security;
alter table cn_demo.sessions enable row level security;
alter table cn_demo.uploads enable row level security;
alter table cn_demo.login_rate_limits enable row level security;
alter table cn_demo.activity_logs enable row level security;

revoke all on all tables in schema cn_demo from public, anon, authenticated;
revoke all on all sequences in schema cn_demo from public, anon, authenticated;
revoke all on all functions in schema cn_demo from public, anon, authenticated;
grant usage on schema cn_demo to service_role;
grant select, insert, update, delete on all tables in schema cn_demo to service_role;
grant usage, select on all sequences in schema cn_demo to service_role;
revoke all on function cn_demo.reset_demo_data(date) from public, anon, authenticated, service_role;
revoke all on function cn_demo.hash_password(text) from public, anon, authenticated;
revoke all on function cn_demo.verify_password(text, text) from public, anon, authenticated;
grant execute on function cn_demo.hash_password(text) to service_role;
grant execute on function cn_demo.verify_password(text, text) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'cn-private',
  'cn-private',
  false,
  2097152,
  array['image/webp', 'image/png', 'image/jpeg']::text[]
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

update demo_control.applications
set database_reset_ready = true, updated_at = clock_timestamp()
where app_id = 'cn';

commit;
